AWSTemplateFormatVersion: 2010-09-09
Description: Test DMS

Parameters:
  ProjectName:
    Description: Project name used for naming and tagging
    Type: String
    Default: testDMS
  TemplateBucket:
    Description: S3 bucket from which nested templates are fetched
    Type: String

Resources:
  vpc:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://s3.amazonaws.com/${TemplateBucket}/testDMS/dms.yaml
      Parameters:
        ProjectName: !Ref ProjectName

# Outputs:
#   # GLOBAL OUTPUTS
#   EipBastion:
#     Description: Bastion EIP
#     Value: !GetAtt vpc.Outputs.OutBastionEIP